image: mortenson/tome
tasks:
  - name: Install tome
    command: |
      COMPOSER_MEMORY_LIMIT=2048M composer install
      [ -d content ] && drush tome:install -y
      gp sync-done install
  - name: Init and login
    init: gp sync-await install
    command: |
      eval $(gp env -e DRUSH_OPTIONS_URI="0.0.0.0:8888")
      [ ! -d content ] && echo "Looks like you haven't initialized a Tome site yet - make sure to composer require any profiles you want to use, then run drush tome:init to get started!"
      [ -d content ] && drush uli
  - name: Runserver
    init: gp sync-await install
    command: [ -d content ] && drush runserver 0.0.0.0:8888
    openMode: split-left
ports:
  - port: 8888
    onOpen: ignore
  - port: 8889
    onOpen: ignore
